### ISSUE TITLE
[Suggestions] Gesture toggle should show hud, invite / request notification

### ISSUE THREAD

**Issue by fwenny** [ddakebono/BTKSAImmersiveHud#1]
Hello. Thank you fod the mod! I was windering if gesture toggle can also show the hud? Its useful to know if I toggled or not.

Regarding invites, could you change so that if a request or an invite arrives, the hud wont turn off until said notification is dismissed?

**Comment by ddakebono** [comment]
Hmm, Gesture Toggle should be visible, strange that it's not.

As for the hud visible till cleared, that should be doable, I could just add it as a config option

**Comment by fwenny** [comment]
So if I toggle gesture from Action menu, it works. If I use the standalone steamvr binding it does not.

**Comment by ddakebono** [comment]
Ahhh, ok. I'm gonna be working on a different method of monitoring for changes today to fix some compatibility issues with other mods, should fix that issue as well.

**Comment by ddakebono** [comment]
Gesture issue fixed in 1.2.0, also adds in the Keep Hud Visible Until Cleared config that will effect Invite/Invite Requests, Friend Requests, Vote Kicks, and notifications added in by other mods.
