### ISSUE TITLE
v1.3.2 No longer hides the HUD

### ISSUE THREAD

**Issue by Dervali-git** [ddakebono/BTKSAImmersiveHud#3]
I noticed this started last night after updating to 1.3.2 and, after rolling back to 1.3.1, it works as expected.

Today, I removed all other mods and tested with just 
BTKSAImmersiveHud v1.3.2
UI Expansion Kit v0.2.3
MelonLoader v0.3.0 ALPHA Pre-Release
and the mic icon remained on the screen indefinitely,

Switching back to 
BTKSAImmersiveHud v1.3.1
UI Expansion Kit v0.2.3
MelonLoader v0.3.0 ALPHA Pre-Release
the mic icon gets disabled after the expected timeout (10 seconds)

I tested this in VR last night and Desktop this morning.

**Comment by ddakebono** [comment]
I think I know what's causing this, pretty sure it was my patch to handle the VRCUiManager hud messages. I'll hopefully be able to get that sorted later today.

**Comment by ddakebono** [comment]
Fixed issue in 1.3.3, was caused by VRCUiManager's hud text popups alpha being set to 1 on startup, but changing to 0.01 after a popup fires.
